### ISSUE TITLE
Track title gets stuck to the first selected track in a queue

### ISSUE THREAD

**Issue by AryToNeX** [mopidy/mopidy-mpd#23] opened 2020-01-14 22:27 UTC
![Screenshot_20200114_232501](https://user-images.githubusercontent.com/13177694/72387976-17c00800-3725-11ea-99a3-5c7dc762bd33.png)

Mopidy 3.0.1 + Mopidy-MPD 3.0.0

**Comment by kingosticks** [comment] 2020-01-14 22:36
What does "selected" mean here? How would someone reproduce this with a generic client such as mpc or netcat?

**Comment by AryToNeX** [comment] 2020-01-14 22:45
@kingosticks selected means the one I first clicked and played. I'm sorry I didn't express myself well enough.

**Comment by kingosticks** [comment] 2020-01-14 23:33
So to reproduce I would:
1. Add a bunch of tracks to the current playlist
2. Start playing one of them (other than the last one)
3. Wait for the track to finish and change to the next one

At which point I would observe the audio has correctly changed but the now-playing status has not, and still incorrectly shows the original track is playing? Correct?

If so, I can't reproduce this with mpc. Can you provide details on what backend these tracks are from (Spotify, or something else?), your `mopidy deps` and a debug log showing the issue, as described at https://docs.mopidy.com/en/latest/troubleshooting/. Thanks.

**Comment by AryToNeX** [comment] 2020-01-15 00:18
The steps to follow are those ones, exactly.

I tried with both mpc and ncmpcpp and I can confirm it doesn't happen there, but it does happen on Cantata, MPD-Discord-Rich-Presence and M.A.L.P.


```
Executable: /usr/bin/mopidy
Platform: Linux-4.19.80-0-vanilla-x86_64-with
Python: CPython 3.8.1 from /usr/lib/python3.8
Mopidy: 3.0.1 from /usr/lib/python3.8/site-packages
  tornado: 6.0.3 from /usr/lib/python3.8/site-packages
  setuptools: 42.0.2.post20191202 from /usr/lib/python3.8/site-packages
  Pykka: 2.0.2 from /usr/lib/python3.8/site-packages
  requests: 2.22.0 from /usr/lib/python3.8/site-packages
    chardet: 3.0.4 from /usr/lib/python3.8/site-packages
    idna: 2.8 from /usr/lib/python3.8/site-packages
    urllib3: 1.25.7 from /usr/lib/python3.8/site-packages
    certifi: 2019.9.11 from /usr/lib/python3.8/site-packages
Mopidy-MusicBox-Webclient: 3.0.1 from /usr/lib/python3.8/site-packages
  Mopidy: 3.0.1 from /usr/lib/python3.8/site-packages
  setuptools: 42.0.2.post20191202 from /usr/lib/python3.8/site-packages
  Pykka: 2.0.2 from /usr/lib/python3.8/site-packages
Mopidy-Scrobbler: 2.0.0 from /usr/lib/python3.8/site-packages
  Mopidy: 3.0.1 from /usr/lib/python3.8/site-packages
  setuptools: 42.0.2.post20191202 from /usr/lib/python3.8/site-packages
  Pykka: 2.0.2 from /usr/lib/python3.8/site-packages
  pylast: 3.2.0 from /usr/lib/python3.8/site-packages
Mopidy-Local: 3.1.0 from /usr/lib/python3.8/site-packages
  Mopidy: 3.0.1 from /usr/lib/python3.8/site-packages
  setuptools: 42.0.2.post20191202 from /usr/lib/python3.8/site-packages
  Pykka: 2.0.2 from /usr/lib/python3.8/site-packages
  uritools: 3.0.0 from /usr/lib/python3.8/site-packages
Mopidy-MPD: 3.0.0 from /usr/lib/python3.8/site-packages
  Mopidy: 3.0.1 from /usr/lib/python3.8/site-packages
  setuptools: 42.0.2.post20191202 from /usr/lib/python3.8/site-packages
  Pykka: 2.0.2 from /usr/lib/python3.8/site-packages
GStreamer: 1.16.2.0 from /usr/lib/python3.8/site-packages/gi
  Detailed information: 
    Python wrapper: python-gi 3.34.0
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        id3demux
        id3v2mux
        lamemp3enc
        mpegaudioparse
        mpg123audiodec
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        pulsesink
        flump3dec
        mad
```

Relevant debugging info when the bug happens:
```
2020-01-15 01:16:16,587 DEBUG [22085:MpdSession-14] mopidy_mpd.session: Response to [::ffff:127.0.0.1]:56158: 
    file: file:///mnt/archive/Musica/Caparezza/Prisoner%20709/02%20Caparezza%20-%20Prisoner%20709%20%28capitolo_%20la%20pena%29.flac
    Time: 237
    Artist: Caparezza
    Album: Prisoner 709
    Title: Prosopagnosia (capitolo: il reato)
    Name: Prisoner 709 (capitolo: la pena)
    Date: 2017-09-15
    Track: 2/16
    Pos: 1
    Id: 10
    MUSICBRAINZ_ALBUMID: 14e5b03e-e372-4547-a768-477e9cf89e33
    AlbumArtist: Caparezza
    MUSICBRAINZ_ALBUMARTISTID: 82462e70-bc00-43ba-8d96-734efa6e72ac
    MUSICBRAINZ_ARTISTID: 82462e70-bc00-43ba-8d96-734efa6e72ac
    Disc: 1
    MUSICBRAINZ_TRACKID: a69413de-453e-48c7-9b4d-300a77e8d18b
    OK
```

and when everything's alright:

```
2020-01-15 01:17:16,151 DEBUG [22085:MpdSession-14] mopidy_mpd.session: Response to [::ffff:127.0.0.1]:56158: 
    file: file:///mnt/archive/Musica/Caparezza/Prisoner%20709/03%20Caparezza%20-%20La%20caduta%20di%20Atlante%20%28capitolo_%20il%20peso%29.flac
    Time: 266
    Artist: Caparezza
    Album: Prisoner 709
    Title: La caduta di Atlante (capitolo: il peso)
    Date: 2017-09-15
    Track: 3/16
    Pos: 2
    Id: 11
    MUSICBRAINZ_ALBUMID: 14e5b03e-e372-4547-a768-477e9cf89e33
    AlbumArtist: Caparezza
    MUSICBRAINZ_ALBUMARTISTID: 82462e70-bc00-43ba-8d96-734efa6e72ac
    MUSICBRAINZ_ARTISTID: 82462e70-bc00-43ba-8d96-734efa6e72ac
    Disc: 1
    MUSICBRAINZ_TRACKID: bf01bf13-dd70-42b3-babf-84d4f2671533
    OK
```

I use Mopidy-Local and my playlists are all based off Mopidy-Local URIs. I also eventually use Mopidy-File. I don't stream over the network.

**Comment by kingosticks** [comment] 2020-01-15 01:23
Could we please have the whole debug log uploaded to dpaste (or similar).

**Comment by AryToNeX** [comment] 2020-01-16 08:47
Sorry for not replying in time. I will edit this comment with the proper log. The problem, for now, is making some test tracks without album cover, as they flood the terminal buffer. So I tried piping to a file, and I got a whopping 700mb log in just seconds of running mopidy (and a log of that size is not practical to upload as a paste). Also, I see I am not the only one having this bug, which is really cool.

**Comment by AryToNeX** [comment] 2020-01-18 03:15
[mopidy.log](https://github.com/mopidy/mopidy-mpd/files/4079909/mopidy.log)

Here's the full log! Sorry for the delay

**Comment by kingosticks** [comment] 2020-01-18 09:07
Thanks. I updated the Mopidy core issue with what I found when reproducing it.

**Comment by kingosticks** [comment] 2020-03-16 23:33
Fixed in https://github.com/mopidy/mopidy/pull/1875

**Closed by kingosticks** 2020-03-16 23:33 UTC
